// This file holds the list of all higher institutions in Nigeria.
// They are grouped into three categories.
// You can add more institutions to any category at any time.

export const INSTITUTIONS = {
  universities: [
    { id: 1, name: 'University of Lagos', abbreviation: 'UNILAG', state: 'Lagos' },
    { id: 2, name: 'University of Ibadan', abbreviation: 'UI', state: 'Oyo' },
    { id: 3, name: 'Obafemi Awolowo University', abbreviation: 'OAU', state: 'Osun' },
    { id: 4, name: 'University of Nigeria Nsukka', abbreviation: 'UNN', state: 'Enugu' },
    { id: 5, name: 'Ahmadu Bello University', abbreviation: 'ABU', state: 'Kaduna' },
    { id: 6, name: 'University of Benin', abbreviation: 'UNIBEN', state: 'Edo' },
    { id: 7, name: 'Lagos State University', abbreviation: 'LASU', state: 'Lagos' },
    { id: 8, name: 'Federal University of Technology Akure', abbreviation: 'FUTA', state: 'Ondo' },
    { id: 9, name: 'Covenant University', abbreviation: 'CU', state: 'Ogun' },
    { id: 10, name: 'University of Port Harcourt', abbreviation: 'UNIPORT', state: 'Rivers' },
    { id: 11, name: 'Nnamdi Azikiwe University', abbreviation: 'UNIZIK', state: 'Anambra' },
    { id: 12, name: 'University of Ilorin', abbreviation: 'UNILORIN', state: 'Kwara' },
    { id: 13, name: 'Bayero University Kano', abbreviation: 'BUK', state: 'Kano' },
    { id: 14, name: 'Delta State University', abbreviation: 'DELSU', state: 'Delta' },
    { id: 15, name: 'Imo State University', abbreviation: 'IMSU', state: 'Imo' },
    { id: 16, name: 'Ambrose Alli University', abbreviation: 'AAU', state: 'Edo' },
    { id: 17, name: 'Ekiti State University', abbreviation: 'EKSU', state: 'Ekiti' },
    { id: 18, name: 'Federal University Oye-Ekiti', abbreviation: 'FUOYE', state: 'Ekiti' },
    { id: 19, name: 'Cross River University of Technology', abbreviation: 'CRUTECH', state: 'Cross River' },
    { id: 20, name: 'University of Calabar', abbreviation: 'UNICAL', state: 'Cross River' },
    { id: 21, name: 'Federal University of Technology Owerri', abbreviation: 'FUTO', state: 'Imo' },
    { id: 22, name: 'Ladoke Akintola University of Technology', abbreviation: 'LAUTECH', state: 'Oyo' },
    { id: 23, name: 'Rivers State University', abbreviation: 'RSU', state: 'Rivers' },
    { id: 24, name: 'Benue State University', abbreviation: 'BSU', state: 'Benue' },
    { id: 25, name: 'Kogi State University', abbreviation: 'KSU', state: 'Kogi' },
  ],

  polytechnics: [
    { id: 101, name: 'Yaba College of Technology', abbreviation: 'YABATECH', state: 'Lagos' },
    { id: 102, name: 'Federal Polytechnic Nekede', abbreviation: 'NEKEDE', state: 'Imo' },
    { id: 103, name: 'Kaduna Polytechnic', abbreviation: 'KADPOLY', state: 'Kaduna' },
    { id: 104, name: 'Federal Polytechnic Ilaro', abbreviation: 'ILAROPOLY', state: 'Ogun' },
    { id: 105, name: 'Federal Polytechnic Bida', abbreviation: 'BIDAPOLY', state: 'Niger' },
    { id: 106, name: 'Akanu Ibiam Federal Polytechnic', abbreviation: 'AIFP', state: 'Ebonyi' },
    { id: 107, name: 'Federal Polytechnic Ede', abbreviation: 'EDEPOLY', state: 'Osun' },
    { id: 108, name: 'Lagos State Polytechnic', abbreviation: 'LASPOTECH', state: 'Lagos' },
    { id: 109, name: 'Rufus Giwa Polytechnic', abbreviation: 'RUGIPO', state: 'Ondo' },
    { id: 110, name: 'Moshood Abiola Polytechnic', abbreviation: 'MAPOLY', state: 'Ogun' },
    { id: 111, name: 'Federal Polytechnic Offa', abbreviation: 'OFFAPOLY', state: 'Kwara' },
    { id: 112, name: 'Federal Polytechnic Oko', abbreviation: 'OKOPOLY', state: 'Anambra' },
    { id: 113, name: 'Auchi Polytechnic', abbreviation: 'AUCHI', state: 'Edo' },
    { id: 114, name: 'Federal Polytechnic Ado-Ekiti', abbreviation: 'FEDPOLYADO', state: 'Ekiti' },
    { id: 115, name: 'Institute of Management and Technology', abbreviation: 'IMT', state: 'Enugu' },
  ],

  collegesOfEducation: [
    { id: 201, name: 'Federal College of Education Zaria', abbreviation: 'FCE Zaria', state: 'Kaduna' },
    { id: 202, name: 'Federal College of Education Abeokuta', abbreviation: 'FCE Abeokuta', state: 'Ogun' },
    { id: 203, name: 'Federal College of Education Kano', abbreviation: 'FCE Kano', state: 'Kano' },
    { id: 204, name: 'Federal College of Education Obudu', abbreviation: 'FCE Obudu', state: 'Cross River' },
    { id: 205, name: 'Adeniran Ogunsanya College of Education', abbreviation: 'AOCOED', state: 'Lagos' },
    { id: 206, name: 'Emmanuel Alayande College of Education', abbreviation: 'EACOED', state: 'Oyo' },
    { id: 207, name: 'Osun State College of Education', abbreviation: 'OSCOED', state: 'Osun' },
    { id: 208, name: 'Imo State College of Education', abbreviation: 'IMOCOE', state: 'Imo' },
    { id: 209, name: 'College of Education Warri', abbreviation: 'COE Warri', state: 'Delta' },
    { id: 210, name: 'Federal College of Education Eha-Amufu', abbreviation: 'FCE Eha-Amufu', state: 'Enugu' },
    { id: 211, name: 'Tai Solarin College of Education', abbreviation: 'TASCE', state: 'Lagos' },
    { id: 212, name: 'Nwafor Orizu College of Education', abbreviation: 'NOCEN', state: 'Anambra' },
    { id: 213, name: 'Federal College of Education Akoka', abbreviation: 'FCE Akoka', state: 'Lagos' },
    { id: 214, name: 'College of Education Gindiri', abbreviation: 'COE Gindiri', state: 'Plateau' },
    { id: 215, name: 'Adeyemi College of Education', abbreviation: 'ACEONDO', state: 'Ondo' },
  ],
};