// This file holds all subjects for each exam body.
// JAMB, WAEC, NECO and NABTEB share mostly the same subjects.
// Post UTME subjects depend on the course the student wants to study
// but we use the common ones here.

export const SUBJECTS = {
  JAMB: [
    'English Language',
    'Mathematics',
    'Biology',
    'Chemistry',
    'Physics',
    'Agriculture',
    'Economics',
    'Government',
    'Literature in English',
    'Geography',
    'Christian Religious Studies',
    'Islamic Religious Studies',
    'Commerce',
    'Accounting',
    'History',
    'Civic Education',
    'French',
    'Yoruba',
    'Igbo',
    'Hausa',
  ],

  WAEC: [
    'English Language',
    'Mathematics',
    'Biology',
    'Chemistry',
    'Physics',
    'Agriculture',
    'Economics',
    'Government',
    'Literature in English',
    'Geography',
    'Christian Religious Studies',
    'Islamic Religious Studies',
    'Commerce',
    'Financial Accounting',
    'History',
    'Civic Education',
    'French',
    'Yoruba',
    'Igbo',
    'Hausa',
    'Further Mathematics',
    'Technical Drawing',
    'Food and Nutrition',
    'Home Economics',
    'Music',
    'Visual Art',
  ],

  NECO: [
    'English Language',
    'Mathematics',
    'Biology',
    'Chemistry',
    'Physics',
    'Agriculture',
    'Economics',
    'Government',
    'Literature in English',
    'Geography',
    'Christian Religious Studies',
    'Islamic Religious Studies',
    'Commerce',
    'Financial Accounting',
    'History',
    'Civic Education',
    'French',
    'Yoruba',
    'Igbo',
    'Hausa',
    'Further Mathematics',
    'Technical Drawing',
    'Food and Nutrition',
    'Home Economics',
  ],

  NABTEB: [
    'English Language',
    'Mathematics',
    'Biology',
    'Chemistry',
    'Physics',
    'Economics',
    'Commerce',
    'Financial Accounting',
    'Auto Mechanics',
    'Building Construction',
    'Electrical Installation',
    'Plumbing and Pipe Fitting',
    'Welding and Fabrication',
    'Woodwork',
    'Catering Craft Practice',
    'Cosmetology',
    'Data Processing',
    'Draughtsmanship',
    'Electronics',
    'Garment Making',
  ],

  POST_UTME: [
    'English Language',
    'Mathematics',
    'Biology',
    'Chemistry',
    'Physics',
    'Economics',
    'Government',
    'Literature in English',
    'Geography',
    'Agriculture',
    'Commerce',
    'Accounting',
    'General Knowledge',
    'Verbal Reasoning',
    'Quantitative Reasoning',
  ],
};